POST http://localhost:3001/api/auth/register 
content-type: application/json

{
    "username": "admin1",
    "password": "admin",
    "firstName": "Admin",
    "lastName": "One",
    "role": "ADMIN"
}

###API
POST http://localhost:3001/api/auth/register 
content-type: application/json

{
    "username": "ARIANASEGURIDAD",
    "password": "23658332",
    "firstName": "Ariana",
    "lastName": "Campos",
    "role": "USER"
}

###
POST http://172.16.2.51:3001/api/auth/register 
content-type: application/json

{
    "username": "JONAIDYSSEGURIDAD",
    "password": "26995987",
    "firstName": "Jonaidys",
    "lastName": "Martinez",
    "role": "USER"
}

###
POST http://172.16.2.51:3001/api/auth/register 
content-type: application/json

{
    "username": "RICHARDSEGURIDAD",
    "password": "12402574",
    "firstName": "Richard",
    "lastName": "Barrera",
    "role": "ADMIN"
}

###
GET http://172.16.2.51:3001/api/visitors/
content-type: application/json

###
GET http://localhost:3001/api/selects/entities
content-type: application/json

###
GET http://localhost:3001/api/selects/administrative-units/1
content-type: application/json

###
GET http://localhost:3001/api/selects/directions/860003000000
content-type: application/json

###
GET http://localhost:3001/api/selects/areas/860004000000?type=unit
content-type: application/json

###
GET http://localhost:3001/api/selects/areas/860003010000?type=direction
content-type: application/json

