POST http://localhost:3001/api/auth/register 
content-type: application/json

{
    "username": "admin1",
    "password": "admin",
    "firstName": "Admin",
    "lastName": "One",
    "role": "ADMIN"
}

###API
POST http://localhost:3001/api/auth/register 
content-type: application/json

{
    "username": "ARIANASEGURIDAD",
    "password": "23658332",
    "firstName": "Ariana",
    "lastName": "Campos",
    "role": "USER"
}

POST http://localhost:3001/api/auth/register 
content-type: application/json

{
    "username": "JONAIDYSSEGURIDAD",
    "password": "26995987",
    "firstName": "Jonaidys ",
    "lastName": "Martinez",
    "role": "USER"
}