export const gerencyOptions = [
  { id: 'PRESIDENCIA', label: 'PRESIDENCIA' },
  { id: 'VICEPRESIDENCIA', label: 'VICEPRESIDENCIA' },
  { id: 'OFICINA DE AUDITORÍA INTERNA', label: 'OFICINA DE AUDITORÍA INTERNA' },
  {
    id: 'OFICINA DE CONSULTORÍA JURÍDICA',
    label: 'OFICINA DE CONSULTORÍA JURÍDICA',
  },
  {
    id: 'OFICINA DE PLANIFICACIÓN, PRESUPUESTO Y ORGANIZACIÓN',
    label: 'OFICINA DE PLANIFICACIÓN, PRESUPUESTO Y ORGANIZACIÓN',
  },
  { id: 'OFICINA DE GESTIÓN HUMANA', label: 'OFICINA DE GESTIÓN HUMANA' },
  {
    id: 'OFICINA DE PROYECTO DE DESARROLLO MINERO',
    label: 'OFICINA DE PROYECTO DE DESARROLLO MINERO',
  },
  {
    id: 'OFICINA DE SEGURIDAD INTEGRAL',
    label: 'OFICINA DE SEGURIDAD INTEGRAL',
  },
  {
    id: 'OFICINA DE ATENCIÓN AL CIUDADANO',
    label: 'OFICINA DE ATENCIÓN AL CIUDADANO',
  },
  {
    id: 'OFICINA DE ADMINISTRACIÓN Y FINANZAS',
    label: 'OFICINA DE ADMINISTRACIÓN Y FINANZAS',
  },
  {
    id: 'OFICINA DE SEGUIMIENTO Y CONTROL',
    label: 'OFICINA DE SEGUIMIENTO Y CONTROL',
  },
  {
    id: 'OFICINA DE GESTIÓN COMUNICACIONAL',
    label: 'OFICINA DE GESTIÓN COMUNICACIONAL',
  },
  {
    id: 'OFICINA DE TECNOLOGÍA DE LA INFORMACIÓN',
    label: 'OFICINA DE TECNOLOGÍA DE LA INFORMACIÓN',
  },
  {
    id: 'GERENCIA GENERAL DE SISTEMATIZACIÓN DEL CATASTRO MINERO',
    label: 'GERENCIA GENERAL DE SISTEMATIZACIÓN DEL CATASTRO MINERO',
  },
  {
    id: 'GERENCIA GENERAL DE GESTIÓN ECOSOCIALISTA',
    label: 'GERENCIA GENERAL DE GESTIÓN ECOSOCIALISTA',
  },
  {
    id: 'GERENCIA GENERAL DE PRODUCCIÓN E INDUSTRIALIZACIÓN MINERA',
    label: 'GERENCIA GENERAL DE PRODUCCIÓN E INDUSTRIALIZACIÓN MINERA',
  },
  {
    id: 'GERENCIA GENERAL DE COMERCIALIZACIÓN',
    label: 'GERENCIA GENERAL DE COMERCIALIZACIÓN',
  },
  { id: 'GERENCIA GENERAL DE REGIONES', label: 'GERENCIA GENERAL DE REGIONES' },
  {
    id: 'GERENCIA OPERACIONAL LOMA DE NÍQUEL',
    label: 'GERENCIA OPERACIONAL LOMA DE NÍQUEL',
  },
  {
    id: 'GERENCIA OPERACIONAL PLANTA DE CHOCÓ',
    label: 'GERENCIA OPERACIONAL PLANTA DE CHOCÓ',
  },
  {
    id: 'GERENCIA OPERACIONAL CARBOSUROESTE',
    label: 'GERENCIA OPERACIONAL CARBOSUROESTE',
  },
  {
    id: 'GERENCIA OPERACIONAL FOSFASUROESTE',
    label: 'GERENCIA OPERACIONAL FOSFASUROESTE',
  },
];

export const phoneOptions = [
  { id: '+58412', label: '+58(412)' },
  { id: '+58414', label: '+58(414)' },
  { id: '+58416', label: '+58(416)' },
  { id: '+58424', label: '+58(424)' },
  { id: '+58426', label: '+58(426)' },
];
